=begin
#CircleCI API

#This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for CircleciOpenapi::InsightsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InsightsApi' do
  before do
    # run before each test
    @api_instance = CircleciOpenapi::InsightsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InsightsApi' do
    it 'should create an instance of InsightsApi' do
      expect(@api_instance).to be_instance_of(CircleciOpenapi::InsightsApi)
    end
  end

  # unit tests for get_project_job_runs
  # Get recent runs of a workflow job
  # Get recent runs of a job within a workflow. Runs going back at most 90 days are returned. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param job_name The name of the job.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [Time] :start_date Include only executions that started at or after this date. This must be specified if an end-date is provided.
  # @option opts [Time] :end_date Include only executions that started before this date. This date can be at most 90 days after the start-date.
  # @return [InlineResponse2005]
  describe 'get_project_job_runs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflow_job_metrics
  # Get summary metrics for a project workflow&#39;s jobs.
  # Get summary metrics for a project workflow&#39;s jobs. Job runs going back at most 90 days are included in the aggregation window. Metrics are refreshed daily, and thus may not include executions from the last 24 hours. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :reporting_window The time window used to calculate summary metrics.
  # @return [InlineResponse2004]
  describe 'get_project_workflow_job_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflow_metrics
  # Get summary metrics for a project&#39;s workflows
  # Get summary metrics for a project&#39;s workflows. Workflow runs going back at most 90 days are included in the aggregation window. Metrics are refreshed daily, and thus may not include executions from the last 24 hours. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :reporting_window The time window used to calculate summary metrics.
  # @return [InlineResponse2002]
  describe 'get_project_workflow_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflow_runs
  # Get recent runs of a workflow
  # Get recent runs of a workflow. Runs going back at most 90 days are returned. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [Time] :start_date Include only executions that started at or after this date. This must be specified if an end-date is provided.
  # @option opts [Time] :end_date Include only executions that started before this date. This date can be at most 90 days after the start-date.
  # @return [InlineResponse2003]
  describe 'get_project_workflow_runs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
