=begin
#CircleCI API

#This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CircleciOpenapi::ProjectVcsInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CircleciOpenapi::ProjectVcsInfo do
  let(:instance) { CircleciOpenapi::ProjectVcsInfo.new }

  describe 'test an instance of ProjectVcsInfo' do
    it 'should create an instance of ProjectVcsInfo' do
      expect(instance).to be_instance_of(CircleciOpenapi::ProjectVcsInfo)
    end
  end
  describe 'test attribute "vcs_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "provider"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Bitbucket", "CircleCI", "GitHub"])
      # validator.allowable_values.each do |value|
      #   expect { instance.provider = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "default_branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
